### ISSUE TITLE
Import from npm install

### ISSUE THREAD

**Issue by EdwinHauspie** [anseki/anim-event#15]
Hello.

I would like to try this script in an existing project. However, when I install from npm, I can't import it. The published package does not seem to support this, but when I look into the source code here on github, it actually does export default.

Any idea?

**Comment by anseki** [comment]
Hi @EdwinHauspie, thank you for the comment.
You can import it by using a bundler such as Webpack.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
